# Docker Compose per Produzione
# Per deploy su server remoto
#
# Per test locale: docker-compose -f docker-compose.prod.yml up -d
# Per produzione: modificare path movies volume

version: '3.8'

services:
  iptv-manager:
    # Per test locale: usa immagine local appena builddata
    image: m3uiptvmanager-iptv-manager:latest
    # Per produzione: usa immagine da Docker Hub
    # image: fpipio/iptv-manager:latest

    container_name: iptv-manager
    restart: unless-stopped
    ports:
      - "3000:3000"  # Cambia se necessario (es: 3010:3000)
    volumes:
      # Database e configurazioni su DISCO LOCALE
      - ./data:/app/data

      # EPG grabber su disco locale (decommentare se lo usi)
      # - ./epg-grabber:/app/epg-grabber

      # Movies su NFS/Network Share (decommentare e modificare path)
      # Per test locale lascia commentato, per produzione decommentare
      # - /media/movies:/app/movies
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
      - OUTPUT_PATH=/app/data/output
    networks:
      - iptv-network

networks:
  iptv-network:
    driver: bridge
